### ISSUE TITLE
send after destroy somewhere

### ISSUE THREAD

**Issue by mafintosh** [mafintosh/dht-rpc#12]
Some part of the code seems to trigger an send after destroy in io.
We should trace that down and fix it.

**Comment by davidmarkclements** [comment]
stack trace from a case using 100 nodes over mininet, with 25% of nodes being destroyed during a scale test (this error occurs roughly 2-3 times in such a scenario), where `destroy` is guarded but `send` is not:
```
Error [ERR_SOCKET_DGRAM_NOT_RUNNING]: Not running
    at Socket._healthCheck (dgram.js:638:11)
    at Socket.send (dgram.js:435:8)
    at IO.send (/home/ubuntu/grenache-grape/node_modules/dht-rpc/lib/io.js:205:17)
    at IO._requestImmediately (/home/ubuntu/grenache-grape/node_modules/dht-rpc/lib/io.js:166:10)
    at IO.queryImmediately (/home/ubuntu/grenache-grape/node_modules/dht-rpc/lib/io.js:262:10)
    at ping (/home/ubuntu/grenache-grape/node_modules/dht-rpc/index.js:259:16)
    at HyperDHT._reping (/home/ubuntu/grenache-grape/node_modules/dht-rpc/index.js:254:5)
    at HyperDHT._onnodeping (/home/ubuntu/grenache-grape/node_modules/dht-rpc/index.js:241:29)
    at emitTwo (events.js:126:13)
    at KBucket.emit (events.js:214:7)
```

**Comment by mafintosh** [comment]
I think we fixed this
