### ISSUE TITLE
Too many request failed error occurring due to TypeError bug

### ISSUE THREAD

**Issue by davidmarkclements** [mafintosh/dht-rpc#31]
When using `swarm.join(discoveryKey)` 

```
Error: Too many requests failed
    at race (/node_modules/dht-rpc/lib/race.js:14:46)
```

If the promises in `race` are logged they look like so:

```
Promise {
    <rejected> TypeError: Cannot read property 'split' of undefined
        at Object.encode (/node_modules/dht-rpc/lib/messages.js:8:21)
        at Object.encode (/node_modules/dht-rpc/lib/messages.js:26:10)
        at Object.encode (/node_modules/compact-encoding/index.js:304:49)
        at annSignable (/node_modules/@hyperswarm/dht/lib/persistent.js:280:26)
        at Function.signAnnounce (/node_modules/@hyperswarm/dht/lib/persistent.js:264:44)
        at commit (/node_modules/@hyperswarm/dht/index.js:394:38)
        at Query.commit [as _commit] (/node_modules/@hyperswarm/dht/index.js:341:14)
        at Query._flush (/node_modules/dht-rpc/lib/query.js:164:54)
        at Query._readMore (/node_modules/dht-rpc/lib/query.js:145:12)
        at Query._onerror (/node_modules/dht-rpc/lib/query.js:206:10)
}
```

Line 8 of messages calls split on the `ip` parameter, the `encode` function there is called rom line 26 of messages, where `peer.host` is passed in. Logging out the peers shows that some of them do not have a `host` property. 

Example of a peer object that causes this error:

```
peer {
  version: 2,
  tid: 57237,
  from: { host: '138.68.164.198', port: 60981 },
  to: { host: '83.160.74.117', port: 52100 },
  id: <Buffer 5b 44 ad 56 71 5f a2 6e d3 5b c1 de 35 10 12 ce 96 e2 9a 8b c2 ec 34 75 f5 6e e1 94 46 8a d1 c3>,
  token: null,
  target: null,
  closerNodes: null,
  command: null,
  status: 0,
  value: null
}
```

**Comment by mafintosh** [comment]
It's a hyperswarm/dht bug, but should be fixed in latest. If not re-open :)

**Comment by ninabreznik** [comment]
Has this been fixed? I just got the same error, but haven't managed to figure out yet if it also comes from missing peer.host.

**Comment by mafintosh** [comment]
Should be fixed. If you see it again post a test case here or in another issue.

**Comment by ninabreznik** [comment]
Ok, will do, thanks
