### ISSUE TITLE
README examples

### ISSUE THREAD

**Issue by sandreae** [mafintosh/dht-rpc#38]
Me and a friendly group p2p enthusiasts had a go at exploring this very interesting library (many thanks for all your hard work!) using the examples in the README and came up against a few difficulties. I'm sure some of it was our own inadequate understanding of the underlying networking logic, but also wondered if you consider the examples to be showing the whole picture, or maybe if they could be set out in a clearer way for people to be able to quite quickly get to a working demo? 

Our concrete error was:

```
Error: Too few nodes responded
    at Query._endAfterCommit (/home/sandreae/Code/hyper-swarm/node_modules/dht-rpc/lib/query.js:195:20)
    at Query._flush (/home/sandreae/Code/hyper-swarm/node_modules/dht-rpc/lib/query.js:190:10)
    at Query._readMore (/home/sandreae/Code/hyper-swarm/node_modules/dht-rpc/lib/query.js:175:12)
    at Query._onerror (/home/sandreae/Code/hyper-swarm/node_modules/dht-rpc/lib/query.js:274:10)
    at Request.destroy (/home/sandreae/Code/hyper-swarm/node_modules/dht-rpc/lib/io.js:296:10)
    at Timeout.oncycle [as _onTimeout] (/home/sandreae/Code/hyper-swarm/node_modules/dht-rpc/lib/io.js:396:9)
    at listOnTimeout (node:internal/timers:559:11)
    at processTimers (node:internal/timers:500:7)
```

We had a publicly addressed bootstrap node running which was successfully receiving queries from nodes we were individually running but then the querying nodes timed out with the above error. We felt like we were missing an important step. 

I understand there is a higher level API in https://github.com/hyperswarm/dht, but we actually chose to explore this lib as we're interested in the underlying functionality for discovery and hole-punching. Maybe you wouldn't recommend this though...

I'm afraid I don't feel I got my head around it enough to draw up any example code suggestions, but if you have pointers of another library we should be using, code we could refer to, or have time to look at the examples here then I'm very happy to test something out and give feedback.

**Comment by cowlicks** [comment]
Did you pass `ephemeral: false` in the options for the DHT constructor?
